# Generated by Django 4.2.6 on 2023-10-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about_image_1',
            field=models.ImageField(default='', upload_to='courses_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='about_image_2',
            field=models.ImageField(default='', upload_to='courses_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='about_image_3',
            field=models.ImageField(default='', upload_to='courses_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='about_text_1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='about_text_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='you_get_text_1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='you_get_text_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='you_get_text_3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='you_get_title_1',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='you_get_title_2',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='you_get_title_3',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
