# Generated by Django 4.2.6 on 2023-10-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_about_image_1_course_about_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='about_text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_get_text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_get_text_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_get_title_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_get_title_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
