# Generated by Django 4.2.6 on 2023-10-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about_image_2',
            field=models.ImageField(default='', upload_to='courses_images'),
            preserve_default=False,
        ),
    ]
