# Generated by Django 4.2.6 on 2023-10-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_about_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
