# Generated by Django 4.2.6 on 2023-10-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
