# Generated by Django 5.0.2 on 2024-02-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about_image_1',
            field=models.ImageField(upload_to='courses_images', verbose_name='Картинка в описании (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='about_image_2',
            field=models.ImageField(upload_to='courses_images', verbose_name='Картинка в описании (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='about_image_3',
            field=models.ImageField(upload_to='courses_images', verbose_name='Картинка в описании (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='about_text_1',
            field=models.TextField(verbose_name='Первое описание курса (Обязательное)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='about_text_2',
            field=models.TextField(blank=True, null=True, verbose_name='Второе описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='header_image',
            field=models.ImageField(upload_to='courses_images/', verbose_name='Картинка заголовка курса (Обязательное)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses_images/', verbose_name='Картинка курса (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена (Обящательно)'),
        ),
    ]
