# Generated by Django 5.0.2 on 2024-02-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_about_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='you_get_text_1',
            field=models.TextField(verbose_name='Описание того, что он получает (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_get_text_2',
            field=models.TextField(blank=True, null=True, verbose_name='Описание того, что он получает'),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_get_text_3',
            field=models.TextField(blank=True, null=True, verbose_name='Описание того, что он получает'),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_get_title_1',
            field=models.CharField(max_length=150, verbose_name='Кратко, что получает пользователь (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_get_title_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кратко, что получает пользователь'),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_get_title_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кратко, что получает пользователь'),
        ),
    ]
