# Generated by Django 5.0.2 on 2024-02-19 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_about_image_1_and_more'),
        ('lessons', '0006_pastlesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description_title',
            field=models.CharField(max_length=150, verbose_name='Описание к уроку (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя урока (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.BigIntegerField(verbose_name='Номер урока (Обязательное)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text',
            field=models.TextField(verbose_name='Основной текст урока (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos', verbose_name='Видео'),
        ),
    ]
