# Generated by Django 4.2.6 on 2023-10-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
