# Generated by Django 4.2.6 on 2023-10-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0005_alter_profile_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users_photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
