# Generated by Django 4.2.6 on 2023-10-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
