# Generated by Django 4.2.6 on 2023-10-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_header_image'),
        ('auth_sys', '0009_alter_profile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(db_table='UserCourses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('St', 'Студент'), ('Te', 'Преподаватель')], default='St'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина')], null=True),
        ),
    ]
