# Generated by Django 4.2.6 on 2023-10-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0010_profile_courses_profile_telegram_profile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Студент', 'Студент'), ('Преподаватель', 'Преподаватель')], default='Студент'),
        ),
    ]
