# Generated by Django 5.0.2 on 2024-02-19 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0012_alter_profile_telephone'),
        ('courses', '0009_alter_course_about_image_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(db_table='UserCourses', to='courses.course', verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина')], null=True, verbose_name='Гендер'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Отчество (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users_photos', verbose_name='Фотография профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия (Обязательно)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на телеграм'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Студент', 'Студент'), ('Преподаватель', 'Преподаватель')], default='Студент', verbose_name='Тип профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь профиля (Обязательно)'),
        ),
    ]
