# Generated by Django 5.0.2 on 2024-02-19 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Вопросы (Обязательно)'),
            preserve_default=False,
        ),
    ]
