# Generated by Django 5.0.2 on 2024-02-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильность ответа (Обязательно)'),
        ),
    ]
