# Generated by Django 4.2.6 on 2023-10-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_siteinfo_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='siteinfo',
            table='SiteInfo',
        ),
    ]
